name: 83323d96dbf46f96b3ea82d181b894b9

on:
  schedule:
    - cron: '0 * * * *' # every hour at minute 0
  workflow_dispatch:

jobs:
  download-adblock-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 83323d96dbf46f96b3ea82d181b894b9
        run: |
          curl -sSL 'https://adbpage.com/adblock?v=3&format=js' -o 83323d96dbf46f96b3ea82d181b894b9.js

      - name: Commit and push june.js
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add 83323d96dbf46f96b3ea82d181b894b9.js
          git diff --cached --quiet || git commit -m "83323d96dbf46f96b3ea82d181b894b9"
          git push
